apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdCluster"
metadata:
  name: rancher-etcd
  annotations:
    etcd.database.coreos.com/scope: clusterwide
spec:
  size: 3
  version: 3.2.26
  pod:
    securityContext:
      runAsNonRoot: true
      runAsUser: 9000
      fsGroup: 9000
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - rancher-etcd
            topologyKey: kubernetes.io/hostname
    persistentVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
  TLS:
    static:
      member:
        peerSecret: tls-rancher-etcd-peer
        serverSecret: tls-rancher-etcd-server
      operatorSecret: tls-rancher-etcd-client
# certs nonsense ? can we use cert-manager?
